sudo: required

compiler:
    - gcc

os:
    - linux

before_script:
    ./autogen.sh

language: c

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - check
            - libblkid-dev
            - libssl-dev
            - gummiboot
            - valgrind
            - lcov

before_install:
  - gem install coveralls-lcov
  - wget -nc --no-check-certificate http://downloads.sourceforge.net/ltp/lcov-1.10.tar.gz
  - tar xzf lcov-1.10.tar.gz
  - cd lcov-1.10 && make && sudo make install
  - cd ..

script:
    - lcov --version | grep "1.10"
    - ./configure --enable-coverage && make && make check && make distcheck && make check-valgrind

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - coveralls-lcov coverage.info
